insert into Student (matricule, name, gender, section) values (1, 'Dracaufeu', 0, 0);
insert into Student (matricule, name, gender, section) values (2, 'Rattata', 0, 0);
insert into Student (matricule, name, gender, section) values (3, 'Pikachu', 1, 1);
insert into Student (matricule, name, gender, section) values (4, 'Rondoudou', 1, 2);
insert into Student (matricule, name, gender, section) values (5, 'Dynavolt', 1, 2);
insert into Student (matricule, name, gender, section) values (6, 'Regice', 0, 1);
insert into Student (matricule, name, gender, section) values (7, 'Rayquaza', 0, 0);

insert into Course (id, title, credits) values ('INT1', 'Introductions', 10);
insert into Course (id, title, credits) values ('MAT1', 'Mathématiques II', 3);
insert into Course (id, title, credits) values ('CAI1', 'Anglais I', 2);
insert into Course (id, title, credits) values ('DEV1', 'Développement I', 10);
insert into Course (id, title, credits) values ('DEV2', 'Développement II', 10);
insert into Course (id, title, credits) values ('WEBG2', 'Développement web I', 5);

insert into Student_Courses values (1, 'INT1');
insert into Student_Courses values (2, 'INT1');
insert into Student_Courses values (3, 'INT1');
insert into Student_Courses values (4, 'INT1');
insert into Student_Courses values (1, 'MAT1');
insert into Student_Courses values (2, 'MAT1');
insert into Student_Courses values (3, 'MAT1');
insert into Student_Courses values (4, 'MAT1');
insert into Student_Courses values (6, 'MAT1');
insert into Student_Courses values (1, 'CAI1');
insert into Student_Courses values (2, 'CAI1');
insert into Student_Courses values (3, 'CAI1');
insert into Student_Courses values (4, 'CAI1');
insert into Student_Courses values (1, 'DEV1');
insert into Student_Courses values (2, 'DEV1');
insert into Student_Courses values (3, 'DEV1');
insert into Student_Courses values (4, 'DEV1');
insert into Student_Courses values (5, 'DEV1');
insert into Student_Courses values (5, 'DEV2');
insert into Student_Courses values (6, 'DEV2');
insert into Student_Courses values (7, 'DEV2');
insert into Student_Courses values (5, 'WEBG2');
insert into Student_Courses values (6, 'WEBG2');
insert into Student_Courses values (7, 'WEBG2');
